### ISSUE TITLE
can ENV use the openai API ?

### ISSUE THREAD

**Issue by rossman22590** [Nashex/gpt4-playground#1]
i have my key in env, why wont app us eit?

**Comment by Nashex** [comment]
Currently, it is set up so that the key is stored on the client side so that was deployable and scalable to the public. However, if you want it to use your env configuration all you would have to do is change [this line](https://github.com/Nashex/gpt4-playground/blob/main/src/pages/api/completion.ts#L31) to pull from the env. You may also want to do some slight refactoring but it should not be more than moving a couple lines.

**Comment by rossman22590** [comment]
so change to this? const token = process.env.OPENAI_API_KEY;
??

**Comment by Nashex** [comment]
Yeah that should work! Just make sure you have pulled down the most recent version.

**Comment by rossman22590** [comment]
it worked!
